drf/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from drf.views import CategoryViewSet,SizeViewSet, ProductPropertyViewSet, ProductViewSet, ListUsers, CartOrderViewSet,CartOrderItemsViewSet
from drf.views import *

router = DefaultRouter()
router.register(r'category', CategoryViewSet,basename='category_api')
router.register(r'size', SizeViewSet,basename='size_api')
router.register(r'product', ProductViewSet,basename='product_api')
router.register(r'productproperty', ProductPropertyViewSet,basename='productproperty_api')
router.register(r'cartorder', CartOrderViewSet,basename='cartorder_api')
router.register(r'cartorderitems', CartOrderItemsViewSet,basename='cartorderitems_api')
urlpatterns =[
    path('api/',include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/users/', ListUsers.as_view()),
    path('api/register/', RegisterUser.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gardening/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('drf.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('category_list', views.category_list, name='category_list'),
    path('product_list', views.product_list, name='product_list'),
    path('category_product_list/<int:cat_id>', views.category_product_list, name='category_product_list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product_detail'),
    path('filter-data', views.filter_data, name='filter_data'),
    path('pagination', views.pagination, name='pagination'),
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('cart', views.cart_list, name='cart'),
    path('delete-from-cart', views.delete_cart_item, name='delete-from-cart'),
    path('update-cart', views.update_cart_item, name='update_cart'),
    path('accounts/profile', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('checkout', views.checkout, name='checkout'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('orders/', views.orders, name='orders'),
    path('order_items/<int:id>', views.order_items, name='order_items'),
    path('cus_orders/', views.cus_orders, name='cus_orders'),
    path('cus_order_items/<int:id>', views.cus_order_items, name='cus_order_items'),

    path('addcategory/', views.add_category,name='addcategory'),
    path('updatecategory/<int:id>/', views.update_category,name='updatecategory'),
    path('deletecategory/<int:id>/', views.delete_category,name='deletecategory'),

    path('addsize/', views.add_size,name='addsize'),
    path('updatesize/<int:id>/', views.update_size,name='updatesize'),
    path('deletesize/<int:id>/', views.delete_size,name='deletesize'),

    path('addproduct/', views.add_product,name='addproduct'),
    path('updateproduct/<int:id>/', views.update_product,name='updateproduct'),
    path('deleteproduct/<int:id>/', views.delete_product,name='deleteproduct'),

    path('addproductp/', views.add_productp,name='addproductp'),
    path('update/<int:id>/', views.update_productp,name='updateproductp'),
    path('delete/<int:id>/', views.delete_productp,name='deleteproductp'),
   
    path('reports/', views.reports,name='reports'),

    path('adminlogin/', views.admin_login,name='adminlogin'),
    path('adminlogout/', views.admin_logout,name='adminlogout'),

    path('updateorder/<int:id>/', views.update_order,name='updateorder'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Create your models here.
#Category
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank= True, upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural = "1. Categories"

    def __str__(self):
        return self.title

#Size    
class Size(models.Model):
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "2. Sizes"

    def __str__(self):
        return self.title

#Product Model
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=500)
    detail = models.TextField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural = "3. Products"

    def __str__(self):
        return self.title

#Product Attribute
class ProductProperty(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural = "4. ProductProperty"

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.product.title

#Order
status_choice=(
        ('process','In Process'),
        ('shipped','Shipped'),
        ('delivered','Delivered'),
    )
class CartOrder(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt=models.FloatField()
    paid_status=models.BooleanField(default=False)
    order_dt=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(choices=status_choice,default='process',max_length=150)

    class Meta:
        verbose_name_plural='5. Orders'

    def __str__(self):
            return self.user.username
# OrderItems 
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    class Meta:
        verbose_name_plural='6. Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))


main/views.py
from urllib import response
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,redirect, HttpResponseRedirect
from .models import Category, Product, ProductProperty, CartOrder,CartOrderItems, Size, User
from django.template.loader import render_to_string
from django.db.models.functions import ExtractMonth
from django.db.models import Count
from .forms import SignupForm, CategoryForm, SizeForm, ProductForm,ProductPropertyForm, LoginForm,CartOrderForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import csv
import datetime
# Create your views here.
# Home Page
def home(request):
    data = Product.objects.filter(is_featured=True).order_by('-id')
    return render(request, "index.html",{'data':data})

# Category Page
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request,'category_list.html',{'data':data})

#Creating product list according to category
def product_list(request):
    total_data =Product.objects.count()
    data = Product.objects.all().order_by('-id')[:3]
    return render(request, 'product_list.html', 
    {
        'data':data,    
        'total_data':total_data,  
    }
    )

#Creating category product list according to category
def category_product_list(request,cat_id):
    category= Category.objects.get(id=cat_id)
    data = Product.objects.filter(category=category).order_by('-id')
    return render(request,'category_product_list.html',
    {
        'data':data,
    }
    )

#product detail 
def product_detail(request,slug,id):
    product = Product.objects.get(id=id)
    sizes=ProductProperty.objects.filter(product=product).values('size__id','size__title','price').distinct()
    return render(request,'product_detail.html',{'data':product,'sizes':sizes})

#Search
def search(request):
    q=request.GET['q']
    data = Product.objects.filter(title__icontains=q).order_by('-id')| \
                Product.objects.filter(detail__icontains=q).order_by('-id')
    return render(request,'search.html',{'data':data})

#Filterdata
def filter_data(request):
    categories = request.GET.getlist('category[]')
    sizes = request.GET.getlist('size[]')
    minPrice = request.GET['minPrice']
    maxPrice = request.GET['maxPrice']
    allProducts = Product.objects.all().order_by('-id').distinct()
    allProducts=allProducts.filter(productproperty__price__gte=minPrice)
    allProducts=allProducts.filter(productproperty__price__lte=maxPrice)

    if len(categories)>0:
        allProducts=allProducts.filter(category__id__in=categories).distinct()
    if len(sizes)>0:  
        allProducts=allProducts.filter(productproperty__size__id__in=sizes).distinct() 
    t = render_to_string('ajax/product_list.html',{'data':allProducts})
    return JsonResponse({'data': t})

# Loadmore Pagination
def pagination(request):
    offset=int(request.GET['offset'])
    limit=int(request.GET['limit'])
    data=Product.objects.all().order_by('-id')[offset:offset+limit]
    t=render_to_string('ajax/product_list.html',{'data':data})
    return JsonResponse({'data':t})

#Add to cart
def add_to_cart(request):
   # del request.session['cartdata']
    cart_p={}
    cart_p[str(request.GET['id'])]={
        'image':request.GET['image'],
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
    }
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request.session['cartdata']:
            cart_data= request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])            
            cart_data.update(cart_data)
            request.session['cartdata']=cart_data
        else:
            cart_data= request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata']=cart_data
    else:
        request.session['cartdata']=cart_p
    return JsonResponse({'data': request.session['cartdata'],'totalitems':len(request.session['cartdata'])})


# Cart List Page
def cart_list(request):
	total_amt=100
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
		return render(request, 'cart.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	else:
		return render(request, 'cart.html',{'cart_data':'','totalitems':0,'total_amt':total_amt})

#Delete Cart Item
def delete_cart_item(request):
    p_id = str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata'] = cart_data
    total_amt=100
    for p_id,item in request.session['cartdata'].items():
        total_amt+= int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart_list.html',{'cart_data': request.session['cartdata'],'totalitems':len(request.session['cartdata']), 'total_amt':total_amt})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

#Update Cart Item
def update_cart_item(request):
    p_id = str(request.GET['id'])
    p_qty= request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=p_qty
            request.session['cartdata'] = cart_data
    total_amt=100
    for p_id,item in request.session['cartdata'].items():
        total_amt+= int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart_list.html',{'cart_data': request.session['cartdata'],'totalitems':len(request.session['cartdata']), 'total_amt':total_amt})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

#Signup
def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            pwd=form.cleaned_data.get('password1')
            user= authenticate(username=username,password=pwd)
            login(request,user)
            return redirect('login')
    form = SignupForm
    return render(request,'registration/signup.html',{'form':form})

#Checkout
@login_required
def checkout(request):
    total_amt=100
    totalAmt=100
    if 'cartdata' in request.session:
        for p_id,item in request.session['cartdata'].items():
            totalAmt+=int(item['qty'])*float(item['price'])
        # Order
        order=CartOrder.objects.create(
                user=request.user,
                total_amt=totalAmt
            )
        # End
        for p_id,item in request.session['cartdata'].items():
            total_amt+=int(item['qty'])*float(item['price'])
            # OrderItems
            items=CartOrderItems.objects.create(
                order=order,
                invoice_no='INV-'+str(order.id),
                item=item['title'],
                image=item['image'],
                qty=item['qty'],
                price=item['price'],
                total=float(item['qty'])*float(item['price'])
                )
            # End
        # Process Payment
        return render(request, 'checkout.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})

#UserDashboard
def user_dashboard(request):
    orders=CartOrder.objects.all()
    return render(request,'user/dashboard.html',{'orders':orders})

#AdminDashboard
import calendar
@staff_member_required
def admin_dashboard(request):
    orders=CartOrder.objects.annotate(month=ExtractMonth('order_dt')).values('month').annotate(count=Count('id')).values('month','count')
    monthNumber=[]
    totalOrders=[]
    for d in orders:
        monthNumber.append(calendar.month_name[d['month']])
        totalOrders.append(d['count'])
    return render(request,'admin/admin_dashboard.html',{'monthNumber': monthNumber,'totalOrders':totalOrders})

#Orders
def orders(request):
    orders = CartOrder.objects.filter(user=request.user).order_by('-id')
    return render(request,'user/orders.html',{'orders':orders})

#orderitems
def order_items(request,id):
    order=CartOrder.objects.get(pk=id)
    orderitems = CartOrderItems.objects.filter(order=order).order_by('-id')
    return render(request,'user/order_items.html',{'orderitems':orderitems})

#Orders
def cus_orders(request):
    orders = CartOrder.objects.all().order_by('-id')
    return render(request,'admin/cus_orders.html',{'orders':orders})

def  update_order(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            si = CartOrder.objects.get(pk=id)
            form = CartOrderForm(request.POST, instance=si)
            if form.is_valid():
                form.save()
        else:
            si = CartOrder.objects.get(pk=id)
        form = CartOrderForm(instance=si)
        return render(request, 'admin/update_order.html',{'form':form,'size':si})
    else:
        return HttpResponseRedirect('/login/')

#orderitems
def cus_order_items(request,id):
    order=CartOrder.objects.get(pk=id)
    orderitems = CartOrderItems.objects.filter(order=order).order_by('-id')
    return render(request,'admin/cus_order_items.html',{'orderitems':orderitems})

#Adding and listing category in admin dashboard
def add_category(request):

main/templates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Gardening System</title>
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'pagination.js' %}"></script>
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="#">Garden Life</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      {% comment %} <li class="nav-item">
		        <a class="nav-link text-white" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category_list' %}">Categories</a>
		      </li> {% endcomment %}
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		           {{request.user.username}}
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		        {% if user.is_authenticated %}
		        	<a class="dropdown-item" href="{% url 'admin_dashboard' %}">Dashboard</a>
		        	<a class="dropdown-item" href="{% url 'adminlogout' %}">Logout</a>
	        	{% else %}
	        		<a class="dropdown-item" href="{% url 'adminlogin' %}">Login</a>
		        {% endif %}
		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>
    
    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
        <div class="col-12 col-md text-center">
        <a href="#">Garden Life</a>
        <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div> 
    </div>
    </footer>
</body>
</html>

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Gardening System</title>
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'pagination.js' %}"></script>
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">Garden Life</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
			<form class="form-inline my-2 my-lg-0" action="/search">
				<div class="input-group">
					<input name="q" type="text" class="form-control" placeholder="search" />
					<div class="input-group-append">
					  <button class="btn btn-dark" type="submit" id="button-addon2">Search</button>
					</div>
				  </div>
			  </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category_list' %}">Categories</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'cart' %}"> Cart (<span class="cart-list">{{request.session.cartdata|length}}</span>)</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		           {{request.user.username}}
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		        {% if user.is_authenticated %}
				<a class="dropdown-item" href="{% url 'user_dashboard' %}">My Profile</a>
				<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
	        	{% else %}
	        	  <a class="dropdown-item" href="{% url 'login' %}">Login</a>
		          <a class="dropdown-item" href="{% url 'signup'%}">Signup</a>
		        {% endif %}
		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>
    
    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
        <div class="col-12 col-md text-center">
        <a href="#">Garden Life</a>
        <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div> 
    </div>
    </footer>
</body>
</html>

main/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<div class="col-md-0">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
                {% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productproperty_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
						<h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6>Rs. {{product.productproperty_set.first.price}}</h6>					  
					</div> 
					</div>
				</div>
			    {% endfor %}
			</div>
		</div>
	</div>
</main>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Recent Added Products</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
        <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productproperty_set.first.image}}" width="350" height="350" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
          <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
          <h6>Rs. {{product.productproperty_set.first.price}}</h6>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product_list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<h3 class="my-4 border-bottom pb-1">{{data.title}}</h3>
	<div class="row">
		<!-- Images -->				
		<div class="col-md-4">
			<img src="/media/{{data.productproperty_set.first.image}}" class="card-img-top" alt="{{data.title}}">
		</div>
		<div class="col-md-8">
			<p>{{data.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Sizes</th>
					<td>
                        {% for size in sizes %}
						<button data-price="{{size.price}}" class="btn btn-outline-secondary btn-sm choose-size size{{size.size__id}}">{{size.size__title}}</button>
                        {% endfor %}
                    </td>
				</tr>
				<tr>
					<th>Price</th>
					<th>Rs. <span class="product-price"> {{data.productproperty_set.first.price}} </span></th>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" value="1" class="form-control" id="productQty" />
			  <div class="input-group-append">
				<input type="hidden" class="product-image" value="{{data.productproperty_set.first.image}}" />
				<input type="hidden" class="product-id" value="{{data.id}}" />
				<input type="hidden" class="product-title" value="{{data.title}}" />
			    <button class="btn btn-primary btn-sm" type="button" id="addToCartBtn"> Add to Cart</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-sm-auto">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Category</th>
					<td><a href="#">{{data.category.title}}</a></td>
				</tr>
				<tr>
					<th>Description</th>
					<td>{{data.desc }}</td>
				</tr>
			</table>
		</div>
	</div>
</main>
<script src="https://cdn.jsdelivr.net/gh/igorlino/elevatezoom-plus@1.2.3/src/jquery.ez-plus.js"></script>
<script src="{% static 'custom.js' %}"></script>
<script src="{% static 'pagination.js' %}"></script>
{% endblock content %}

main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
                {% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
						<a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productproperty_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
						<div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6>Rs. {{product.productproperty_set.first.price}}</h6> 
					</div>
					</div>
				</div>
			    {% endfor %}
			</div>
			<p class="my-4 text-center"><button id ="pagination"  data-limit="3" data-total="{{total_data}}" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search result for </span>{{request.GET.q}}</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
        <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productproperty_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
				<h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
				<h6>Rs. {{product.productproperty_set.first.price}}</h6> 			 
			</div>
		</div>
    {% endfor %}
	</div>
</main>
{% endblock %}